import { useState, useMemo, useEffect, useCallback } from 'react';
import { useCollaborators } from '@/hooks/useCollaborators';
import { useVtConfig, useUpdateVtConfig, useVtMonthly, useUpsertVtMonthly, useUpdateVtMonthlySaldo } from '@/hooks/useValeTransporte';
import { useAuth } from '@/contexts/AuthContext';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { useToast } from '@/hooks/use-toast';
import { Download, Save, Bus, Settings, Users, DollarSign, Building2, CreditCard, Upload } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useQueryClient } from '@tanstack/react-query';
import * as XLSX from 'xlsx';

const MONTHS = ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];

export default function ValeTransporte() {
  const now = new Date();
  const [selectedMonth, setSelectedMonth] = useState(now.getMonth() + 1);
  const [selectedYear, setSelectedYear] = useState(now.getFullYear());
  const { toast } = useToast();
  const { usuario, session } = useAuth();
  const isAdmin = usuario?.perfil === 'admin';

  const { data: vtConfig } = useVtConfig();
  const updateConfig = useUpdateVtConfig();
  const { data: collaborators = [] } = useCollaborators();
  const { data: vtMonthly = [], isLoading } = useVtMonthly(selectedMonth, selectedYear);
  const upsertVt = useUpsertVtMonthly();
  const updateSaldo = useUpdateVtMonthlySaldo();

  const [valorPassagem, setValorPassagem] = useState('');
  const [localSaldos, setLocalSaldos] = useState<Record<string, string>>({});
  const [localRecargas, setLocalRecargas] = useState<Record<string, string>>({});
  const [importProgress, setImportProgress] = useState<string | null>(null);
  const [importDone, setImportDone] = useState(false);
  const queryClient = useQueryClient();

  useEffect(() => {
    if (vtConfig) setValorPassagem(String(vtConfig.valor_passagem));
  }, [vtConfig]);

  // Collaborators with VT active (sorted alphabetically by full name, pt-BR)
  const vtCollabs = useMemo(() =>
    collaborators
      .filter(c => c.status !== 'DESLIGADO' && (c as any).vt_ativo === true)
      .slice()
      .sort((a, b) =>
        (a.collaborator_name || '').localeCompare(b.collaborator_name || '', 'pt-BR', { sensitivity: 'base' })
      ),
    [collaborators]
  );

  const vp = vtConfig?.valor_passagem ?? 7.70;
  const PCT_DESCONTO = 0.06;

  // Map monthly records by collaborator_id
  const monthlyMap = useMemo(() => {
    const map: Record<string, typeof vtMonthly[0]> = {};
    vtMonthly.forEach(r => { map[r.collaborator_id] = r; });
    return map;
  }, [vtMonthly]);

  // Auto-generate records when month has no data
  const [autoGenerated, setAutoGenerated] = useState(false);
  useEffect(() => {
    if (isLoading || autoGenerated) return;
    if (vtCollabs.length === 0) return;
    const missing = vtCollabs.filter(c => !monthlyMap[c.id]);
    if (missing.length > 0 && vtMonthly.length === 0) {
      const rows = missing.map(c => {
        const passagensDia = (c as any).vt_passagens_dia ?? 2;
        const diasMes = (c as any).vt_dias_mes ?? 26;
        const totalPassagens = passagensDia * diasMes;
        const recargaIntegral = +(totalPassagens * vp).toFixed(2);
        return {
          collaborator_id: c.id,
          month: selectedMonth,
          year: selectedYear,
          saldo_cartao: null,
          recarga_integral: recargaIntegral,
          recarga_necessaria: null,
          desconto_folha: null,
          custo_empresa: null,
          created_by: session?.user?.id || null,
        };
      });
      upsertVt.mutate(rows as any);
      setAutoGenerated(true);
    }
  }, [vtCollabs, monthlyMap, vtMonthly, isLoading, selectedMonth, selectedYear, vp, session, autoGenerated, upsertVt]);

  // Reset auto-generated flag on month change
  useEffect(() => { setAutoGenerated(false); setLocalSaldos({}); setLocalRecargas({}); }, [selectedMonth, selectedYear]);

  // Build display rows
  const rows = useMemo(() => {
    return vtCollabs.map(c => {
      const passagensDia = (c as any).vt_passagens_dia ?? 2;
      const diasMes = (c as any).vt_dias_mes ?? 26;
      const totalPassagens = passagensDia * diasMes;
      const recargaCalc = +(totalPassagens * vp).toFixed(2);
      const record = monthlyMap[c.id];
      // Allow override of recarga_integral from DB or local edit
      const recargaOverrideStr = localRecargas[c.id];
      const recargaFromDb = record?.recarga_integral;
      let recargaIntegral = recargaCalc;
      let recargaOverridden = false;
      if (recargaOverrideStr !== undefined && recargaOverrideStr !== '') {
        const parsed = parseFloat(recargaOverrideStr.replace(',', '.'));
        if (!isNaN(parsed)) { recargaIntegral = parsed; recargaOverridden = Math.abs(parsed - recargaCalc) > 0.01; }
      } else if (recargaFromDb != null && Math.abs(recargaFromDb - recargaCalc) > 0.01) {
        recargaIntegral = recargaFromDb;
        recargaOverridden = true;
      }
      const recargaStr = localRecargas[c.id] ?? (recargaOverridden ? String(recargaIntegral) : '');
      const saldoStr = localSaldos[c.id] ?? (record?.saldo_cartao != null ? String(record.saldo_cartao) : '');
      const saldoCartao = saldoStr !== '' ? parseFloat(saldoStr.replace(',', '.')) : null;
      const recargaNecessaria = saldoCartao != null ? Math.max(0, +(recargaIntegral - saldoCartao).toFixed(2)) : null;
      const creditoExcedente = saldoCartao != null && (recargaIntegral - saldoCartao) < 0;
      const salarioBase = (c as any).salario_base as number | null;
      const limiteDesconto = salarioBase != null ? +(salarioBase * PCT_DESCONTO).toFixed(2) : null;
      const descontoFolha = recargaNecessaria != null && limiteDesconto != null ? Math.min(recargaNecessaria, limiteDesconto) : null;
      const custoEmpresa = recargaNecessaria != null && descontoFolha != null ? +(recargaNecessaria - descontoFolha).toFixed(2) : null;

      return {
        id: c.id,
        recordId: record?.id,
        name: c.collaborator_name,
        sector: c.sector,
        passagensDia,
        diasMes,
        totalPassagens,
        recargaCalc,
        recargaIntegral,
        recargaOverridden,
        recargaStr,
        saldoStr,
        saldoCartao,
        recargaNecessaria,
        creditoExcedente,
        salarioBase,
        limiteDesconto,
        descontoFolha,
        custoEmpresa,
      };
    });
  }, [vtCollabs, monthlyMap, localSaldos, localRecargas, vp]);

  const totals = useMemo(() => {
    let recargaTotal = 0, recargaNecTotal = 0, descontoTotal = 0, custoTotal = 0;
    rows.forEach(r => {
      recargaTotal += r.recargaIntegral;
      recargaNecTotal += r.recargaNecessaria ?? 0;
      descontoTotal += r.descontoFolha ?? 0;
      custoTotal += r.custoEmpresa ?? 0;
    });
    return { recargaTotal, recargaNecTotal, descontoTotal, custoTotal };
  }, [rows]);

  const handleSaldoChange = (collabId: string, value: string) => {
    setLocalSaldos(prev => ({ ...prev, [collabId]: value }));
  };

  const handleRecargaChange = (collabId: string, value: string) => {
    setLocalRecargas(prev => ({ ...prev, [collabId]: value }));
  };

  const handleSaldoBlur = useCallback(async (row: typeof rows[0]) => {
    if (!row.recordId) return;
    try {
      await updateSaldo.mutateAsync({
        id: row.recordId,
        saldo_cartao: row.saldoCartao,
        recarga_integral: row.recargaIntegral,
        recarga_necessaria: row.recargaNecessaria,
        desconto_folha: row.descontoFolha,
        custo_empresa: row.custoEmpresa,
      });
    } catch {
      toast({ title: 'Erro ao salvar', variant: 'destructive' });
    }
  }, [updateSaldo, toast]);

  const handleSaveAll = async () => {
    const updates = rows.filter(r => r.recordId).map(r => ({
      collaborator_id: r.id,
      month: selectedMonth,
      year: selectedYear,
      saldo_cartao: r.saldoCartao,
      recarga_integral: r.recargaIntegral,
      recarga_necessaria: r.recargaNecessaria,
      desconto_folha: r.descontoFolha,
      custo_empresa: r.custoEmpresa,
      created_by: session?.user?.id || null,
    }));
    try {
      await upsertVt.mutateAsync(updates as any);
      toast({ title: 'Todos os registros salvos' });
    } catch {
      toast({ title: 'Erro ao salvar', variant: 'destructive' });
    }
  };

  const handleSaveConfig = async () => {
    if (!vtConfig || !session?.user?.id) return;
    const val = parseFloat(valorPassagem.replace(',', '.'));
    if (isNaN(val) || val <= 0) { toast({ title: 'Valor inválido', variant: 'destructive' }); return; }
    try {
      await updateConfig.mutateAsync({ id: vtConfig.id, valor_passagem: val, updated_by: session.user.id });
      toast({ title: 'Valor da passagem atualizado' });
    } catch {
      toast({ title: 'Erro ao atualizar', variant: 'destructive' });
    }
  };

  const handleExport = () => {
    const data = rows.map(r => ({
      Colaborador: r.name,
      Setor: r.sector,
      'Passagens/dia': r.passagensDia,
      Dias: r.diasMes,
      'Total passagens': r.totalPassagens,
      'Recarga integral (R$)': r.recargaIntegral,
      'Saldo cartão (R$)': r.saldoCartao ?? '',
      'Recarga necessária (R$)': r.recargaNecessaria ?? '',
      'Salário base (R$)': r.salarioBase ?? '',
      'Limite desconto (R$)': r.limiteDesconto ?? '',
      'Desconto folha (R$)': r.descontoFolha ?? '',
      'Custo empresa (R$)': r.custoEmpresa ?? '',
    }));
    const ws = XLSX.utils.json_to_sheet(data);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Vale Transporte');
    XLSX.writeFile(wb, `vale-transporte-${String(selectedMonth).padStart(2, '0')}-${selectedYear}.xlsx`);
  };

  const fmt = (v: number | null) => v != null ? v.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 }) : '—';

  // === IMPORT VT MARÇO (temporary) ===
  const handleImportMarco = async () => {
    if (!session?.user?.id) return;
    const colaboradores = [
      { nome: "ALICIA", salario_base: 1625.00 },
      { nome: "ALINE", salario_base: 2592.00 },
      { nome: "CICERO", salario_base: 2369.00 },
      { nome: "GLEPSON", salario_base: 2771.00 },
      { nome: "JAVIER", salario_base: 2592.00 },
      { nome: "JENIFFER", salario_base: 2168.00 },
      { nome: "SHEYLA", salario_base: 2146.00 },
      { nome: "WELLINGTON", salario_base: 1775.00 },
      { nome: "VILSON", salario_base: 1755.00 },
    ];
    const saldosMap: Record<string, number> = {
      "ALICIA": 7.80, "ALINE": 79.80, "CICERO": 189.90, "GLEPSON": 123.00,
      "JAVIER": 123.00, "JENIFFER": 212.55, "SHEYLA": 0.60, "WELLINGTON": 6.75, "VILSON": 0.00,
    };
    try {
      for (let i = 0; i < colaboradores.length; i++) {
        const c = colaboradores[i];
        setImportProgress(`Atualizando colaborador ${i + 1} de ${colaboradores.length}: ${c.nome}...`);
        await supabase.from('collaborators').update({
          salario_base: c.salario_base, vt_ativo: true, vt_passagens_dia: 2, vt_dias_mes: 26,
        } as any).ilike('collaborator_name', c.nome + '%');
      }
      setImportProgress('Buscando colaboradores atualizados...');
      const { data: updatedCollabs } = await supabase.from('collaborators').select('id, collaborator_name').eq('vt_ativo', true);
      if (!updatedCollabs) throw new Error('Falha ao buscar colaboradores');
      const VP = 7.70;
      for (let i = 0; i < colaboradores.length; i++) {
        const c = colaboradores[i];
        setImportProgress(`Criando registro VT ${i + 1} de ${colaboradores.length}: ${c.nome}...`);
        const collab = updatedCollabs.find(u => u.collaborator_name.toUpperCase().startsWith(c.nome));
        if (!collab) continue;
        const isVilson = c.nome === 'VILSON';
        const recargaIntegral = isVilson ? 134.00 : +(2 * 26 * VP).toFixed(2);
        const saldo = saldosMap[c.nome] ?? 0;
        const recargaNec = Math.max(0, +(recargaIntegral - saldo).toFixed(2));
        const limite = +(c.salario_base * 0.06).toFixed(2);
        const desconto = Math.min(recargaNec, limite);
        const custo = +(recargaNec - desconto).toFixed(2);
        await supabase.from('vt_monthly').upsert({
          collaborator_id: collab.id, month: 3, year: 2026,
          saldo_cartao: saldo, recarga_integral: recargaIntegral,
          recarga_necessaria: recargaNec, desconto_folha: desconto,
          custo_empresa: custo, created_by: session.user.id,
        } as any, { onConflict: 'collaborator_id,month,year' });
      }
      setImportProgress('Concluído! Recarregando dados...');
      await queryClient.invalidateQueries({ queryKey: ['collaborators'] });
      await queryClient.invalidateQueries({ queryKey: ['vt_monthly', 3, 2026] });
      setSelectedMonth(3);
      setSelectedYear(2026);
      setImportDone(true);
      toast({ title: 'Importação de VT Março/2026 concluída!' });
    } catch (err: any) {
      toast({ title: 'Erro na importação', description: err.message, variant: 'destructive' });
    } finally {
      setTimeout(() => setImportProgress(null), 3000);
    }
  };

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2"><Bus className="w-6 h-6" /> Vale Transporte</h1>
          <p className="text-sm text-muted-foreground">Gestão mensal de vale transporte</p>
        </div>
        <div className="flex flex-wrap gap-2">
          <Select value={String(selectedMonth)} onValueChange={v => setSelectedMonth(Number(v))}>
            <SelectTrigger className="w-[140px]"><SelectValue /></SelectTrigger>
            <SelectContent>{MONTHS.map((m, i) => <SelectItem key={i} value={String(i + 1)}>{m}</SelectItem>)}</SelectContent>
          </Select>
          <Select value={String(selectedYear)} onValueChange={v => setSelectedYear(Number(v))}>
            <SelectTrigger className="w-[100px]"><SelectValue /></SelectTrigger>
            <SelectContent>{[2025, 2026, 2027].map(y => <SelectItem key={y} value={String(y)}>{y}</SelectItem>)}</SelectContent>
          </Select>
          <Button variant="outline" size="sm" onClick={handleExport} disabled={rows.length === 0}>
            <Download className="w-4 h-4 mr-1" /> Excel
          </Button>
          <Button size="sm" onClick={handleSaveAll} disabled={upsertVt.isPending}>
            <Save className="w-4 h-4 mr-1" /> Salvar tudo
          </Button>
          {isAdmin && !importDone && (
            <Button size="sm" variant="outline" onClick={handleImportMarco} disabled={!!importProgress} className="border-amber-500 text-amber-700 hover:bg-amber-50">
              <Upload className="w-4 h-4 mr-1" /> Importar VT Março
            </Button>
          )}
        </div>
      </div>

      {importProgress && (
        <Card className="border-amber-300 bg-amber-50">
          <CardContent className="p-4">
            <p className="text-sm font-medium text-amber-800">{importProgress}</p>
            <Progress className="mt-2 h-2" value={importProgress.includes('Concluído') ? 100 : undefined} />
          </CardContent>
        </Card>
      )}

      {/* Summary cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Card><CardContent className="p-4 flex items-center gap-3">
          <Users className="w-8 h-8 text-primary" />
          <div><p className="text-xs text-muted-foreground">Colaboradores VT</p><p className="text-xl font-bold">{vtCollabs.length}</p></div>
        </CardContent></Card>
        <Card><CardContent className="p-4 flex items-center gap-3">
          <CreditCard className="w-8 h-8 text-blue-500" />
          <div><p className="text-xs text-muted-foreground">Recarga total</p><p className="text-xl font-bold">R$ {fmt(totals.recargaTotal)}</p></div>
        </CardContent></Card>
        <Card><CardContent className="p-4 flex items-center gap-3">
          <DollarSign className="w-8 h-8 text-amber-500" />
          <div><p className="text-xs text-muted-foreground">Desconto folha</p><p className="text-xl font-bold">R$ {fmt(totals.descontoTotal)}</p></div>
        </CardContent></Card>
        <Card><CardContent className="p-4 flex items-center gap-3">
          <Building2 className="w-8 h-8 text-emerald-500" />
          <div><p className="text-xs text-muted-foreground">Custo empresa</p><p className="text-xl font-bold">R$ {fmt(totals.custoTotal)}</p></div>
        </CardContent></Card>
      </div>

      {/* Config */}
      {isAdmin && (
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-4 flex-wrap">
              <Settings className="w-5 h-5 text-muted-foreground" />
              <div className="space-y-1">
                <Label className="text-xs">Valor da passagem (R$)</Label>
                <div className="flex gap-2">
                  <Input className="w-32" value={valorPassagem} onChange={e => setValorPassagem(e.target.value)} placeholder="7.70" />
                  <Button size="sm" onClick={handleSaveConfig} disabled={updateConfig.isPending}>Salvar</Button>
                </div>
              </div>
              <div className="text-xs text-muted-foreground border-l pl-4">
                <p className="font-medium">Desconto CLT: 6%</p>
                <p>Lei 7.418/85 — Art. 4º, parágrafo único</p>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Main table */}
      {isLoading ? (
        <p className="text-muted-foreground">Carregando...</p>
      ) : rows.length === 0 ? (
        <Card><CardContent className="py-12 text-center text-muted-foreground">
          Nenhum colaborador com Vale Transporte ativo. Configure o VT no cadastro de colaboradores.
        </CardContent></Card>
      ) : (
        <Card className="border">
          <CardContent className="p-0 overflow-auto">
            <Table>
              <TableHeader>
                <TableRow className="bg-muted/50">
                  <TableHead className="font-bold">Colaborador</TableHead>
                  <TableHead>Setor</TableHead>
                  <TableHead className="text-center">Pass./dia</TableHead>
                  <TableHead className="text-center">Dias</TableHead>
                  <TableHead className="text-center">Total</TableHead>
                  <TableHead className="text-right">Recarga integral</TableHead>
                  <TableHead className="text-right">Saldo cartão</TableHead>
                  <TableHead className="text-right">Recarga nec.</TableHead>
                  <TableHead className="text-right">Salário base</TableHead>
                  <TableHead className="text-right">Limite desc.</TableHead>
                  <TableHead className="text-right">Desc. folha</TableHead>
                  <TableHead className="text-right">Custo empresa</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {rows.map((r, idx) => (
                  <TableRow key={r.id} className={idx % 2 === 1 ? 'bg-muted/20' : ''}>
                    <TableCell className="font-medium">{r.name}</TableCell>
                    <TableCell className="text-xs">{r.sector}</TableCell>
                    <TableCell className="text-center">{r.passagensDia}</TableCell>
                    <TableCell className="text-center">{r.diasMes}</TableCell>
                    <TableCell className="text-center">{r.totalPassagens}</TableCell>
                    <TableCell className="text-right p-1">
                      <Input
                        className={`h-7 w-24 text-right text-xs ml-auto ${r.recargaOverridden ? 'border-amber-400 bg-amber-50' : ''}`}
                        value={r.recargaStr}
                        onChange={e => handleRecargaChange(r.id, e.target.value)}
                        onBlur={() => handleSaldoBlur(r)}
                        onKeyDown={e => { if (e.key === 'Enter') handleSaldoBlur(r); }}
                        placeholder={fmt(r.recargaCalc)}
                      />
                    </TableCell>
                    <TableCell className="text-right p-1">
                      <Input
                        className="h-7 w-24 text-right text-xs ml-auto"
                        value={r.saldoStr}
                        onChange={e => handleSaldoChange(r.id, e.target.value)}
                        onBlur={() => handleSaldoBlur(r)}
                        onKeyDown={e => { if (e.key === 'Enter') handleSaldoBlur(r); }}
                        placeholder="0,00"
                      />
                    </TableCell>
                    <TableCell className="text-right">
                      {r.creditoExcedente ? (
                        <Badge variant="secondary" className="bg-emerald-100 text-emerald-700 text-[10px]">Crédito excedente</Badge>
                      ) : fmt(r.recargaNecessaria)}
                    </TableCell>
                    <TableCell className="text-right text-xs">{r.salarioBase != null ? fmt(r.salarioBase) : <span className="text-muted-foreground">—</span>}</TableCell>
                    <TableCell className="text-right text-xs">{fmt(r.limiteDesconto)}</TableCell>
                    <TableCell className="text-right font-medium">{fmt(r.descontoFolha)}</TableCell>
                    <TableCell className="text-right font-medium">{r.custoEmpresa != null && r.custoEmpresa > 0 ? fmt(r.custoEmpresa) : r.custoEmpresa === 0 ? '—' : fmt(r.custoEmpresa)}</TableCell>
                  </TableRow>
                ))}
                {/* Totals row */}
                <TableRow className="bg-muted/50 font-bold border-t-2">
                  <TableCell colSpan={5} className="text-right">TOTAIS</TableCell>
                  <TableCell className="text-right">{fmt(totals.recargaTotal)}</TableCell>
                  <TableCell />
                  <TableCell className="text-right">{fmt(totals.recargaNecTotal)}</TableCell>
                  <TableCell />
                  <TableCell />
                  <TableCell className="text-right">{fmt(totals.descontoTotal)}</TableCell>
                  <TableCell className="text-right">{fmt(totals.custoTotal)}</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
