ALTER TABLE public.collaborators
  ADD COLUMN salario_base NUMERIC(10,2) DEFAULT NULL,
  ADD COLUMN vt_ativo BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN vt_passagens_dia INTEGER NOT NULL DEFAULT 2,
  ADD COLUMN vt_dias_mes INTEGER DEFAULT NULL;